### PR TITLE
Fix build break on stable channel

### PR DESCRIPTION
**Pull request by kei10in**
This pull request enables stable / beta / nightly build.

### CODE REVIEW

**Comment by kevinswiber** [comment]
Thanks for the PR, @kei10in!  If we're adding a feature here anyway, why don't we just make it `sse4`?  Any issue with this?  Check out #2 to see it.

**Comment by kei10in** [comment]
Probably there is no issues. I just kept using `target_feature`.
Adding a feature is simple and nice.

**Comment by kevinswiber** [comment]
Thanks for the contribution, @kei10in!  Merged!  Are you using this in a project or just playing around?

**Comment by kei10in** [comment]
I'm using this project as a comparison target of http parser developing experimentally.
[Httparse](https://crates.io/crates/httparse) is using [pico-sys](https://crates.io/crates/pico-sys) in this way. But pico-sys is old and not maitained.
I'm glad to be published at Crates.io.

**Comment by kevinswiber** [comment]
I’d recommend benchmarking with the SIMD PR on Httparse as well as with the sse4 feature on this project. Curious to see the results!

**Comment by kei10in** [comment]
Thanks for information, @kevinswiber.
I didn't know httparse SIMD PR and I tried it.

The result is here.

https://gist.github.com/kei10in/2c2f11d27833f5f02c67c8a1117c795c

**Comment by kevinswiber** [comment]
@kei10in Rad!

FYI: Just published this as v1.0.0.  https://crates.io/crates/picohttpparser-sys

**Pull request merged**
